import re

with open("app/src/main/java/com/example/ui/screens/AutomaticSmsScreen.kt", "r") as f:
    content = f.read()

# Add the missing state variables
state_vars = """
    var rulePayConfirm by remember { mutableStateOf(AutomaticSmsManager.isRulePaymentConfirmationEnabled(context)) }
    var ruleDueReminder by remember { mutableStateOf(AutomaticSmsManager.isRuleDueReminderEnabled(context)) }
    var ruleBillGenerated by remember { mutableStateOf(AutomaticSmsManager.isRuleBillGeneratedEnabled(context)) }
    var ruleOverdue by remember { mutableStateOf(AutomaticSmsManager.isRuleOverdueEnabled(context)) }
    var ruleGeneralNotice by remember { mutableStateOf(AutomaticSmsManager.isRuleGeneralNoticeEnabled(context)) }
"""

content = re.sub(r'    var rulePayConfirm by remember.*?isRuleDueReminderEnabled\(context\)\) \}', state_vars.strip(), content, flags=re.DOTALL)

# Add the missing RuleCards
missing_cards = """
        // Bill Generated
        item {
            RuleCard(
                title = if (isBn) "📝 বিল তৈরির বার্তা (Bill Generated Message)" else "📝 Bill Generated Message",
                checked = ruleBillGenerated,
                onCheckedChange = {
                    ruleBillGenerated = it
                    AutomaticSmsManager.setRuleBillGeneratedEnabled(context, it)
                },
                onEditClick = {
                    onEditTemplate("bill_generated", if (isBn) "বিল তৈরির বার্তা" else "Bill Generated Message", AutomaticSmsManager.getTemplateBillGenerated(context))
                },
                isBn = isBn
            )
        }

        // Overdue Bill
        item {
            RuleCard(
                title = if (isBn) "🚫 বকেয়া নোটিশ (Overdue Notice)" else "🚫 Overdue Notice",
                checked = ruleOverdue,
                onCheckedChange = {
                    ruleOverdue = it
                    AutomaticSmsManager.setRuleOverdueEnabled(context, it)
                },
                onEditClick = {
                    onEditTemplate("overdue", if (isBn) "বকেয়া নোটিশ" else "Overdue Notice", AutomaticSmsManager.getTemplateOverdue(context))
                },
                isBn = isBn
            )
        }

        // General Notice
        item {
            RuleCard(
                title = if (isBn) "📢 সাধারণ নোটিশ (General Notice)" else "📢 General Notice",
                checked = ruleGeneralNotice,
                onCheckedChange = {
                    ruleGeneralNotice = it
                    AutomaticSmsManager.setRuleGeneralNoticeEnabled(context, it)
                },
                onEditClick = {
                    onEditTemplate("general_notice", if (isBn) "সাধারণ নোটিশ" else "General Notice", AutomaticSmsManager.getTemplateGeneralNotice(context))
                },
                isBn = isBn
            )
        }
"""

content = content.replace("        // Bill Paid", missing_cards.strip() + "\n\n        // Bill Paid")

with open("app/src/main/java/com/example/ui/screens/AutomaticSmsScreen.kt", "w") as f:
    f.write(content)

